---@class kec.controls
kec.controls = {}

kec.controls.keys = {
    INPUT_NEXT_CAMERA = 0, -- Index: 0, Default QWERTY: V, Xbox Controller: BACK
    INPUT_LOOK_LR = 1, -- Index: 1, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_LOOK_UD = 2, -- Index: 2, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_LOOK_UP_ONLY = 3, -- Index: 3, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_LOOK_DOWN_ONLY = 4, -- Index: 4, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_LOOK_LEFT_ONLY = 5, -- Index: 5, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_LOOK_RIGHT_ONLY = 6, -- Index: 6, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_CINEMATIC_SLOWMO = 7, -- Index: 7, Default QWERTY: (NONE), Xbox Controller: R3
    INPUT_SCRIPTED_FLY_UD = 8, -- Index: 8, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_SCRIPTED_FLY_LR = 9, -- Index: 9, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_SCRIPTED_FLY_ZUP = 10, -- Index: 10, Default QWERTY: PAGEUP, Xbox Controller: LT
    INPUT_SCRIPTED_FLY_ZDOWN = 11, -- Index: 11, Default QWERTY: PAGEDOWN, Xbox Controller: RT
    INPUT_WEAPON_WHEEL_UD = 12, -- Index: 12, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_WEAPON_WHEEL_LR = 13, -- Index: 13, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_WEAPON_WHEEL_NEXT = 14, -- Index: 14, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: DPAD RIGHT
    INPUT_WEAPON_WHEEL_PREV = 15, -- Index: 15, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: DPAD LEFT
    INPUT_SELECT_NEXT_WEAPON = 16, -- Index: 16, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: (NONE)
    INPUT_SELECT_PREV_WEAPON = 17, -- Index: 17, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: (NONE)
    INPUT_SKIP_CUTSCENE = 18, -- Index: 18, Default QWERTY: ENTER / LEFT MOUSE BUTTON / SPACEBAR, Xbox Controller: A
    INPUT_CHARACTER_WHEEL = 19, -- Index: 19, Default QWERTY: LEFT ALT, Xbox Controller: DPAD DOWN
    INPUT_MULTIPLAYER_INFO = 20, -- Index: 20, Default QWERTY: Z, Xbox Controller: DPAD DOWN
    INPUT_SPRINT = 21, -- Index: 21, Default QWERTY: LEFT SHIFT, Xbox Controller: A
    INPUT_JUMP = 22, -- Index: 22, Default QWERTY: SPACEBAR, Xbox Controller: X
    INPUT_ENTER = 23, -- Index: 23, Default QWERTY: F, Xbox Controller: Y
    INPUT_ATTACK = 24, -- Index: 24, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RT
    INPUT_AIM = 25, -- Index: 25, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: LT
    INPUT_LOOK_BEHIND = 26, -- Index: 26, Default QWERTY: C, Xbox Controller: R3
    INPUT_PHONE = 27, -- Index: 27, Default QWERTY: ARROW UP / SCROLLWHEEL BUTTON (PRESS), Xbox Controller: DPAD UP
    INPUT_SPECIAL_ABILITY = 28, -- Index: 28, Default QWERTY: (NONE), Xbox Controller: L3
    INPUT_SPECIAL_ABILITY_SECONDARY = 29, -- Index: 29, Default QWERTY: B, Xbox Controller: R3
    INPUT_MOVE_LR = 30, -- Index: 30, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_MOVE_UD = 31, -- Index: 31, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_MOVE_UP_ONLY = 32, -- Index: 32, Default QWERTY: W, Xbox Controller: LEFT STICK
    INPUT_MOVE_DOWN_ONLY = 33, -- Index: 33, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_MOVE_LEFT_ONLY = 34, -- Index: 34, Default QWERTY: A, Xbox Controller: LEFT STICK
    INPUT_MOVE_RIGHT_ONLY = 35, -- Index: 35, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_DUCK = 36, -- Index: 36, Default QWERTY: LEFT CTRL, Xbox Controller: L3
    INPUT_SELECT_WEAPON = 37, -- Index: 37, Default QWERTY: TAB, Xbox Controller: LB
    INPUT_PICKUP = 38, -- Index: 38, Default QWERTY: E, Xbox Controller: LB
    INPUT_SNIPER_ZOOM = 39, -- Index: 39, Default QWERTY: [, Xbox Controller: LEFT STICK
    INPUT_SNIPER_ZOOM_IN_ONLY = 40, -- Index: 40, Default QWERTY: ], Xbox Controller: LEFT STICK
    INPUT_SNIPER_ZOOM_OUT_ONLY = 41, -- Index: 41, Default QWERTY: [, Xbox Controller: LEFT STICK
    INPUT_SNIPER_ZOOM_IN_SECONDARY = 42, -- Index: 42, Default QWERTY: ], Xbox Controller: DPAD UP
    INPUT_SNIPER_ZOOM_OUT_SECONDARY = 43, -- Index: 43, Default QWERTY: [, Xbox Controller: DPAD DOWN
    INPUT_COVER = 44, -- Index: 44, Default QWERTY: Q, Xbox Controller: RB
    INPUT_RELOAD = 45, -- Index: 45, Default QWERTY: R, Xbox Controller: B
    INPUT_TALK = 46, -- Index: 46, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_DETONATE = 47, -- Index: 47, Default QWERTY: G, Xbox Controller: DPAD LEFT
    INPUT_HUD_SPECIAL = 48, -- Index: 48, Default QWERTY: Z, Xbox Controller: DPAD DOWN
    INPUT_ARREST = 49, -- Index: 49, Default QWERTY: F, Xbox Controller: Y
    INPUT_ACCURATE_AIM = 50, -- Index: 50, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: R3
    INPUT_CONTEXT = 51, -- Index: 51, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_CONTEXT_SECONDARY = 52, -- Index: 52, Default QWERTY: Q, Xbox Controller: DPAD LEFT
    INPUT_WEAPON_SPECIAL = 53, -- Index: 53, Default QWERTY: (NONE), Xbox Controller: Y
    INPUT_WEAPON_SPECIAL_TWO = 54, -- Index: 54, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_DIVE = 55, -- Index: 55, Default QWERTY: SPACEBAR, Xbox Controller: RB
    INPUT_DROP_WEAPON = 56, -- Index: 56, Default QWERTY: F9, Xbox Controller: Y
    INPUT_DROP_AMMO = 57, -- Index: 57, Default QWERTY: F10, Xbox Controller: B
    INPUT_THROW_GRENADE = 58, -- Index: 58, Default QWERTY: G, Xbox Controller: DPAD LEFT
    INPUT_VEH_MOVE_LR = 59, -- Index: 59, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_UD = 60, -- Index: 60, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_UP_ONLY = 61, -- Index: 61, Default QWERTY: LEFT SHIFT, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_DOWN_ONLY = 62, -- Index: 62, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_LEFT_ONLY = 63, -- Index: 63, Default QWERTY: A, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_RIGHT_ONLY = 64, -- Index: 64, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_SPECIAL = 65, -- Index: 65, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_VEH_GUN_LR = 66, -- Index: 66, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_GUN_UD = 67, -- Index: 67, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_VEH_AIM = 68, -- Index: 68, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: LB
    INPUT_VEH_ATTACK = 69, -- Index: 69, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RB
    INPUT_VEH_ATTACK2 = 70, -- Index: 70, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: A
    INPUT_VEH_ACCELERATE = 71, -- Index: 71, Default QWERTY: W, Xbox Controller: RT
    INPUT_VEH_BRAKE = 72, -- Index: 72, Default QWERTY: S, Xbox Controller: LT
    INPUT_VEH_DUCK = 73, -- Index: 73, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_HEADLIGHT = 74, -- Index: 74, Default QWERTY: H, Xbox Controller: DPAD RIGHT
    INPUT_VEH_EXIT = 75, -- Index: 75, Default QWERTY: F, Xbox Controller: Y
    INPUT_VEH_HANDBRAKE = 76, -- Index: 76, Default QWERTY: SPACEBAR, Xbox Controller: RB
    INPUT_VEH_HOTWIRE_LEFT = 77, -- Index: 77, Default QWERTY: W, Xbox Controller: LT
    INPUT_VEH_HOTWIRE_RIGHT = 78, -- Index: 78, Default QWERTY: S, Xbox Controller: RT
    INPUT_VEH_LOOK_BEHIND = 79, -- Index: 79, Default QWERTY: C, Xbox Controller: R3
    INPUT_VEH_CIN_CAM = 80, -- Index: 80, Default QWERTY: R, Xbox Controller: B
    INPUT_VEH_NEXT_RADIO = 81, -- Index: 81, Default QWERTY: ., Xbox Controller: (NONE)
    INPUT_VEH_PREV_RADIO = 82, -- Index: 82, Default QWERTY: ,, Xbox Controller: (NONE)
    INPUT_VEH_NEXT_RADIO_TRACK = 83, -- Index: 83, Default QWERTY: =, Xbox Controller: (NONE)
    INPUT_VEH_PREV_RADIO_TRACK = 84, -- Index: 84, Default QWERTY: -, Xbox Controller: (NONE)
    INPUT_VEH_RADIO_WHEEL = 85, -- Index: 85, Default QWERTY: Q, Xbox Controller: DPAD LEFT
    INPUT_VEH_HORN = 86, -- Index: 86, Default QWERTY: E, Xbox Controller: L3
    INPUT_VEH_FLY_THROTTLE_UP = 87, -- Index: 87, Default QWERTY: W, Xbox Controller: RT
    INPUT_VEH_FLY_THROTTLE_DOWN = 88, -- Index: 88, Default QWERTY: S, Xbox Controller: LT
    INPUT_VEH_FLY_YAW_LEFT = 89, -- Index: 89, Default QWERTY: A, Xbox Controller: LB
    INPUT_VEH_FLY_YAW_RIGHT = 90, -- Index: 90, Default QWERTY: D, Xbox Controller: RB
    INPUT_VEH_PASSENGER_AIM = 91, -- Index: 91, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: LT
    INPUT_VEH_PASSENGER_ATTACK = 92, -- Index: 92, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RT
    INPUT_VEH_SPECIAL_ABILITY_FRANKLIN = 93, -- Index: 93, Default QWERTY: (NONE), Xbox Controller: R3
    INPUT_VEH_STUNT_UD = 94, -- Index: 94, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_VEH_CINEMATIC_UD = 95, -- Index: 95, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_VEH_CINEMATIC_UP_ONLY = 96, -- Index: 96, Default QWERTY: NUMPAD- / SCROLLWHEEL UP, Xbox Controller: (NONE)
    INPUT_VEH_CINEMATIC_DOWN_ONLY = 97, -- Index: 97, Default QWERTY: NUMPAD+ / SCROLLWHEEL DOWN, Xbox Controller: (NONE)
    INPUT_VEH_CINEMATIC_LR = 98, -- Index: 98, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_SELECT_NEXT_WEAPON = 99, -- Index: 99, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: X
    INPUT_VEH_SELECT_PREV_WEAPON = 100, -- Index: 100, Default QWERTY: [, Xbox Controller: (NONE)
    INPUT_VEH_ROOF = 101, -- Index: 101, Default QWERTY: H, Xbox Controller: DPAD RIGHT
    INPUT_VEH_JUMP = 102, -- Index: 102, Default QWERTY: SPACEBAR, Xbox Controller: RB
    INPUT_VEH_GRAPPLING_HOOK = 103, -- Index: 103, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_VEH_SHUFFLE = 104, -- Index: 104, Default QWERTY: H, Xbox Controller: DPAD RIGHT
    INPUT_VEH_DROP_PROJECTILE = 105, -- Index: 105, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_MOUSE_CONTROL_OVERRIDE = 106, -- Index: 106, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_VEH_FLY_ROLL_LR = 107, -- Index: 107, Default QWERTY: NUMPAD 6, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_ROLL_LEFT_ONLY = 108, -- Index: 108, Default QWERTY: NUMPAD 4, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_ROLL_RIGHT_ONLY = 109, -- Index: 109, Default QWERTY: NUMPAD 6, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_PITCH_UD = 110, -- Index: 110, Default QWERTY: NUMPAD 5, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_PITCH_UP_ONLY = 111, -- Index: 111, Default QWERTY: NUMPAD 8, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_PITCH_DOWN_ONLY = 112, -- Index: 112, Default QWERTY: NUMPAD 5, Xbox Controller: LEFT STICK
    INPUT_VEH_FLY_UNDERCARRIAGE = 113, -- Index: 113, Default QWERTY: G, Xbox Controller: L3
    INPUT_VEH_FLY_ATTACK = 114, -- Index: 114, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: A
    INPUT_VEH_FLY_SELECT_NEXT_WEAPON = 115, -- Index: 115, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: DPAD LEFT
    INPUT_VEH_FLY_SELECT_PREV_WEAPON = 116, -- Index: 116, Default QWERTY: [, Xbox Controller: (NONE)
    INPUT_VEH_FLY_SELECT_TARGET_LEFT = 117, -- Index: 117, Default QWERTY: NUMPAD 7, Xbox Controller: LB
    INPUT_VEH_FLY_SELECT_TARGET_RIGHT = 118, -- Index: 118, Default QWERTY: NUMPAD 9, Xbox Controller: RB
    INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE = 119, -- Index: 119, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_VEH_FLY_DUCK = 120, -- Index: 120, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_FLY_ATTACK_CAMERA = 121, -- Index: 121, Default QWERTY: INSERT, Xbox Controller: R3
    INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE = 122, -- Index: 122, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_VEH_SUB_TURN_LR = 123, -- Index: 123, Default QWERTY: NUMPAD 6, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_TURN_LEFT_ONLY = 124, -- Index: 124, Default QWERTY: NUMPAD 4, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_TURN_RIGHT_ONLY = 125, -- Index: 125, Default QWERTY: NUMPAD 6, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_PITCH_UD = 126, -- Index: 126, Default QWERTY: NUMPAD 5, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_PITCH_UP_ONLY = 127, -- Index: 127, Default QWERTY: NUMPAD 8, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_PITCH_DOWN_ONLY = 128, -- Index: 128, Default QWERTY: NUMPAD 5, Xbox Controller: LEFT STICK
    INPUT_VEH_SUB_THROTTLE_UP = 129, -- Index: 129, Default QWERTY: W, Xbox Controller: RT
    INPUT_VEH_SUB_THROTTLE_DOWN = 130, -- Index: 130, Default QWERTY: S, Xbox Controller: LT
    INPUT_VEH_SUB_ASCEND = 131, -- Index: 131, Default QWERTY: LEFT SHIFT, Xbox Controller: X
    INPUT_VEH_SUB_DESCEND = 132, -- Index: 132, Default QWERTY: LEFT CTRL, Xbox Controller: A
    INPUT_VEH_SUB_TURN_HARD_LEFT = 133, -- Index: 133, Default QWERTY: A, Xbox Controller: LB
    INPUT_VEH_SUB_TURN_HARD_RIGHT = 134, -- Index: 134, Default QWERTY: D, Xbox Controller: RB
    INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE = 135, -- Index: 135, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_VEH_PUSHBIKE_PEDAL = 136, -- Index: 136, Default QWERTY: W, Xbox Controller: A
    INPUT_VEH_PUSHBIKE_SPRINT = 137, -- Index: 137, Default QWERTY: CAPSLOCK, Xbox Controller: A
    INPUT_VEH_PUSHBIKE_FRONT_BRAKE = 138, -- Index: 138, Default QWERTY: Q, Xbox Controller: LT
    INPUT_VEH_PUSHBIKE_REAR_BRAKE = 139, -- Index: 139, Default QWERTY: S, Xbox Controller: RT
    INPUT_MELEE_ATTACK_LIGHT = 140, -- Index: 140, Default QWERTY: R, Xbox Controller: B
    INPUT_MELEE_ATTACK_HEAVY = 141, -- Index: 141, Default QWERTY: Q, Xbox Controller: A
    INPUT_MELEE_ATTACK_ALTERNATE = 142, -- Index: 142, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RT
    INPUT_MELEE_BLOCK = 143, -- Index: 143, Default QWERTY: SPACEBAR, Xbox Controller: X
    INPUT_PARACHUTE_DEPLOY = 144, -- Index: 144, Default QWERTY: F / LEFT MOUSE BUTTON, Xbox Controller: Y
    INPUT_PARACHUTE_DETACH = 145, -- Index: 145, Default QWERTY: F, Xbox Controller: Y
    INPUT_PARACHUTE_TURN_LR = 146, -- Index: 146, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_TURN_LEFT_ONLY = 147, -- Index: 147, Default QWERTY: A, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_TURN_RIGHT_ONLY = 148, -- Index: 148, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_PITCH_UD = 149, -- Index: 149, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_PITCH_UP_ONLY = 150, -- Index: 150, Default QWERTY: W, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_PITCH_DOWN_ONLY = 151, -- Index: 151, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_PARACHUTE_BRAKE_LEFT = 152, -- Index: 152, Default QWERTY: Q, Xbox Controller: LB
    INPUT_PARACHUTE_BRAKE_RIGHT = 153, -- Index: 153, Default QWERTY: E, Xbox Controller: RB
    INPUT_PARACHUTE_SMOKE = 154, -- Index: 154, Default QWERTY: X, Xbox Controller: A
    INPUT_PARACHUTE_PRECISION_LANDING = 155, -- Index: 155, Default QWERTY: LEFT SHIFT, Xbox Controller: (NONE)
    INPUT_MAP = 156, -- Index: 156, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_UNARMED = 157, -- Index: 157, Default QWERTY: 1, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_MELEE = 158, -- Index: 158, Default QWERTY: 2, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_HANDGUN = 159, -- Index: 159, Default QWERTY: 6, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_SHOTGUN = 160, -- Index: 160, Default QWERTY: 3, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_SMG = 161, -- Index: 161, Default QWERTY: 7, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_AUTO_RIFLE = 162, -- Index: 162, Default QWERTY: 8, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_SNIPER = 163, -- Index: 163, Default QWERTY: 9, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_HEAVY = 164, -- Index: 164, Default QWERTY: 4, Xbox Controller: (NONE)
    INPUT_SELECT_WEAPON_SPECIAL = 165, -- Index: 165, Default QWERTY: 5, Xbox Controller: (NONE)
    INPUT_SELECT_CHARACTER_MICHAEL = 166, -- Index: 166, Default QWERTY: F5, Xbox Controller: (NONE)
    INPUT_SELECT_CHARACTER_FRANKLIN = 167, -- Index: 167, Default QWERTY: F6, Xbox Controller: (NONE)
    INPUT_SELECT_CHARACTER_TREVOR = 168, -- Index: 168, Default QWERTY: F7, Xbox Controller: (NONE)
    INPUT_SELECT_CHARACTER_MULTIPLAYER = 169, -- Index: 169, Default QWERTY: F8 (CONSOLE), Xbox Controller: (NONE)
    INPUT_SAVE_REPLAY_CLIP = 170, -- Index: 170, Default QWERTY: F3, Xbox Controller: B
    INPUT_SPECIAL_ABILITY_PC = 171, -- Index: 171, Default QWERTY: CAPSLOCK, Xbox Controller: (NONE)
    INPUT_CELLPHONE_UP = 172, -- Index: 172, Default QWERTY: ARROW UP, Xbox Controller: DPAD UP
    INPUT_CELLPHONE_DOWN = 173, -- Index: 173, Default QWERTY: ARROW DOWN, Xbox Controller: DPAD DOWN
    INPUT_CELLPHONE_LEFT = 174, -- Index: 174, Default QWERTY: ARROW LEFT, Xbox Controller: DPAD LEFT
    INPUT_CELLPHONE_RIGHT = 175, -- Index: 175, Default QWERTY: ARROW RIGHT, Xbox Controller: DPAD RIGHT
    INPUT_CELLPHONE_SELECT = 176, -- Index: 176, Default QWERTY: ENTER / LEFT MOUSE BUTTON, Xbox Controller: A
    INPUT_CELLPHONE_CANCEL = 177, -- Index: 177, Default QWERTY: BACKSPACE / ESC / RIGHT MOUSE BUTTON, Xbox Controller: B
    INPUT_CELLPHONE_OPTION = 178, -- Index: 178, Default QWERTY: DELETE, Xbox Controller: Y
    INPUT_CELLPHONE_EXTRA_OPTION = 179, -- Index: 179, Default QWERTY: SPACEBAR, Xbox Controller: X
    INPUT_CELLPHONE_SCROLL_FORWARD = 180, -- Index: 180, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: (NONE)
    INPUT_CELLPHONE_SCROLL_BACKWARD = 181, -- Index: 181, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: (NONE)
    INPUT_CELLPHONE_CAMERA_FOCUS_LOCK = 182, -- Index: 182, Default QWERTY: L, Xbox Controller: RT
    INPUT_CELLPHONE_CAMERA_GRID = 183, -- Index: 183, Default QWERTY: G, Xbox Controller: RB
    INPUT_CELLPHONE_CAMERA_SELFIE = 184, -- Index: 184, Default QWERTY: E, Xbox Controller: R3
    INPUT_CELLPHONE_CAMERA_DOF = 185, -- Index: 185, Default QWERTY: F, Xbox Controller: LB
    INPUT_CELLPHONE_CAMERA_EXPRESSION = 186, -- Index: 186, Default QWERTY: X, Xbox Controller: L3
    INPUT_FRONTEND_DOWN = 187, -- Index: 187, Default QWERTY: ARROW DOWN, Xbox Controller: DPAD DOWN
    INPUT_FRONTEND_UP = 188, -- Index: 188, Default QWERTY: ARROW UP, Xbox Controller: DPAD UP
    INPUT_FRONTEND_LEFT = 189, -- Index: 189, Default QWERTY: ARROW LEFT, Xbox Controller: DPAD LEFT
    INPUT_FRONTEND_RIGHT = 190, -- Index: 190, Default QWERTY: ARROW RIGHT, Xbox Controller: DPAD RIGHT
    INPUT_FRONTEND_RDOWN = 191, -- Index: 191, Default QWERTY: ENTER, Xbox Controller: A
    INPUT_FRONTEND_RUP = 192, -- Index: 192, Default QWERTY: TAB, Xbox Controller: Y
    INPUT_FRONTEND_RLEFT = 193, -- Index: 193, Default QWERTY: (NONE), Xbox Controller: X
    INPUT_FRONTEND_RRIGHT = 194, -- Index: 194, Default QWERTY: BACKSPACE, Xbox Controller: B
    INPUT_FRONTEND_AXIS_X = 195, -- Index: 195, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_FRONTEND_AXIS_Y = 196, -- Index: 196, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_FRONTEND_RIGHT_AXIS_X = 197, -- Index: 197, Default QWERTY: ], Xbox Controller: RIGHT STICK
    INPUT_FRONTEND_RIGHT_AXIS_Y = 198, -- Index: 198, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: RIGHT STICK
    INPUT_FRONTEND_PAUSE = 199, -- Index: 199, Default QWERTY: P, Xbox Controller: START
    INPUT_FRONTEND_PAUSE_ALTERNATE = 200, -- Index: 200, Default QWERTY: ESC, Xbox Controller: (NONE)
    INPUT_FRONTEND_ACCEPT = 201, -- Index: 201, Default QWERTY: ENTER / NUMPAD ENTER, Xbox Controller: A
    INPUT_FRONTEND_CANCEL = 202, -- Index: 202, Default QWERTY: BACKSPACE / ESC, Xbox Controller: B
    INPUT_FRONTEND_X = 203, -- Index: 203, Default QWERTY: SPACEBAR, Xbox Controller: X
    INPUT_FRONTEND_Y = 204, -- Index: 204, Default QWERTY: TAB, Xbox Controller: Y
    INPUT_FRONTEND_LB = 205, -- Index: 205, Default QWERTY: Q, Xbox Controller: LB
    INPUT_FRONTEND_RB = 206, -- Index: 206, Default QWERTY: E, Xbox Controller: RB
    INPUT_FRONTEND_LT = 207, -- Index: 207, Default QWERTY: PAGE DOWN, Xbox Controller: LT
    INPUT_FRONTEND_RT = 208, -- Index: 208, Default QWERTY: PAGE UP, Xbox Controller: RT
    INPUT_FRONTEND_LS = 209, -- Index: 209, Default QWERTY: LEFT SHIFT, Xbox Controller: L3
    INPUT_FRONTEND_RS = 210, -- Index: 210, Default QWERTY: LEFT CONTROL, Xbox Controller: R3
    INPUT_FRONTEND_LEADERBOARD = 211, -- Index: 211, Default QWERTY: TAB, Xbox Controller: RB
    INPUT_FRONTEND_SOCIAL_CLUB = 212, -- Index: 212, Default QWERTY: HOME, Xbox Controller: BACK
    INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY = 213, -- Index: 213, Default QWERTY: HOME, Xbox Controller: RB
    INPUT_FRONTEND_DELETE = 214, -- Index: 214, Default QWERTY: DELETE, Xbox Controller: X
    INPUT_FRONTEND_ENDSCREEN_ACCEPT = 215, -- Index: 215, Default QWERTY: ENTER, Xbox Controller: A
    INPUT_FRONTEND_ENDSCREEN_EXPAND = 216, -- Index: 216, Default QWERTY: SPACEBAR, Xbox Controller: X
    INPUT_FRONTEND_SELECT = 217, -- Index: 217, Default QWERTY: CAPSLOCK, Xbox Controller: BACK
    INPUT_SCRIPT_LEFT_AXIS_X = 218, -- Index: 218, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_SCRIPT_LEFT_AXIS_Y = 219, -- Index: 219, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_SCRIPT_RIGHT_AXIS_X = 220, -- Index: 220, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_SCRIPT_RIGHT_AXIS_Y = 221, -- Index: 221, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_SCRIPT_RUP = 222, -- Index: 222, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: Y
    INPUT_SCRIPT_RDOWN = 223, -- Index: 223, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: A
    INPUT_SCRIPT_RLEFT = 224, -- Index: 224, Default QWERTY: LEFT CTRL, Xbox Controller: X
    INPUT_SCRIPT_RRIGHT = 225, -- Index: 225, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: B
    INPUT_SCRIPT_LB = 226, -- Index: 226, Default QWERTY: (NONE), Xbox Controller: LB
    INPUT_SCRIPT_RB = 227, -- Index: 227, Default QWERTY: (NONE), Xbox Controller: RB
    INPUT_SCRIPT_LT = 228, -- Index: 228, Default QWERTY: (NONE), Xbox Controller: LT
    INPUT_SCRIPT_RT = 229, -- Index: 229, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RT
    INPUT_SCRIPT_LS = 230, -- Index: 230, Default QWERTY: (NONE), Xbox Controller: L3
    INPUT_SCRIPT_RS = 231, -- Index: 231, Default QWERTY: (NONE), Xbox Controller: R3
    INPUT_SCRIPT_PAD_UP = 232, -- Index: 232, Default QWERTY: W, Xbox Controller: DPAD UP
    INPUT_SCRIPT_PAD_DOWN = 233, -- Index: 233, Default QWERTY: S, Xbox Controller: DPAD DOWN
    INPUT_SCRIPT_PAD_LEFT = 234, -- Index: 234, Default QWERTY: A, Xbox Controller: DPAD LEFT
    INPUT_SCRIPT_PAD_RIGHT = 235, -- Index: 235, Default QWERTY: D, Xbox Controller: DPAD RIGHT
    INPUT_SCRIPT_SELECT = 236, -- Index: 236, Default QWERTY: V, Xbox Controller: BACK
    INPUT_CURSOR_ACCEPT = 237, -- Index: 237, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_CURSOR_CANCEL = 238, -- Index: 238, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_CURSOR_X = 239, -- Index: 239, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_CURSOR_Y = 240, -- Index: 240, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_CURSOR_SCROLL_UP = 241, -- Index: 241, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: (NONE)
    INPUT_CURSOR_SCROLL_DOWN = 242, -- Index: 242, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: (NONE)
    INPUT_ENTER_CHEAT_CODE = 243, -- Index: 243, Default QWERTY: ~ / `, Xbox Controller: (NONE)
    INPUT_INTERACTION_MENU = 244, -- Index: 244, Default QWERTY: M, Xbox Controller: BACK
    INPUT_MP_TEXT_CHAT_ALL = 245, -- Index: 245, Default QWERTY: T, Xbox Controller: (NONE)
    INPUT_MP_TEXT_CHAT_TEAM = 246, -- Index: 246, Default QWERTY: Y, Xbox Controller: (NONE)
    INPUT_MP_TEXT_CHAT_FRIENDS = 247, -- Index: 247, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_MP_TEXT_CHAT_CREW = 248, -- Index: 248, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_PUSH_TO_TALK = 249, -- Index: 249, Default QWERTY: N, Xbox Controller: (NONE)
    INPUT_CREATOR_LS = 250, -- Index: 250, Default QWERTY: R, Xbox Controller: L3
    INPUT_CREATOR_RS = 251, -- Index: 251, Default QWERTY: F, Xbox Controller: R3
    INPUT_CREATOR_LT = 252, -- Index: 252, Default QWERTY: X, Xbox Controller: LT
    INPUT_CREATOR_RT = 253, -- Index: 253, Default QWERTY: C, Xbox Controller: RT
    INPUT_CREATOR_MENU_TOGGLE = 254, -- Index: 254, Default QWERTY: LEFT SHIFT, Xbox Controller: (NONE)
    INPUT_CREATOR_ACCEPT = 255, -- Index: 255, Default QWERTY: SPACEBAR, Xbox Controller: A
    INPUT_CREATOR_DELETE = 256, -- Index: 256, Default QWERTY: DELETE, Xbox Controller: X
    INPUT_ATTACK2 = 257, -- Index: 257, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: RT
    INPUT_RAPPEL_JUMP = 258, -- Index: 258, Default QWERTY: (NONE), Xbox Controller: A
    INPUT_RAPPEL_LONG_JUMP = 259, -- Index: 259, Default QWERTY: (NONE), Xbox Controller: X
    INPUT_RAPPEL_SMASH_WINDOW = 260, -- Index: 260, Default QWERTY: (NONE), Xbox Controller: RT
    INPUT_PREV_WEAPON = 261, -- Index: 261, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: DPAD LEFT
    INPUT_NEXT_WEAPON = 262, -- Index: 262, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: DPAD RIGHT
    INPUT_MELEE_ATTACK1 = 263, -- Index: 263, Default QWERTY: R, Xbox Controller: B
    INPUT_MELEE_ATTACK2 = 264, -- Index: 264, Default QWERTY: Q, Xbox Controller: A
    INPUT_WHISTLE = 265, -- Index: 265, Default QWERTY: (NONE), Xbox Controller: (NONE)
    INPUT_MOVE_LEFT = 266, -- Index: 266, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_MOVE_RIGHT = 267, -- Index: 267, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_MOVE_UP = 268, -- Index: 268, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_MOVE_DOWN = 269, -- Index: 269, Default QWERTY: S, Xbox Controller: LEFT STICK
    INPUT_LOOK_LEFT = 270, -- Index: 270, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_LOOK_RIGHT = 271, -- Index: 271, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_LOOK_UP = 272, -- Index: 272, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_LOOK_DOWN = 273, -- Index: 273, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_SNIPER_ZOOM_IN = 274, -- Index: 274, Default QWERTY: [, Xbox Controller: RIGHT STICK
    INPUT_SNIPER_ZOOM_OUT = 275, -- Index: 275, Default QWERTY: [, Xbox Controller: RIGHT STICK
    INPUT_SNIPER_ZOOM_IN_ALTERNATE = 276, -- Index: 276, Default QWERTY: [, Xbox Controller: LEFT STICK
    INPUT_SNIPER_ZOOM_OUT_ALTERNATE = 277, -- Index: 277, Default QWERTY: [, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_LEFT = 278, -- Index: 278, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_RIGHT = 279, -- Index: 279, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_UP = 280, -- Index: 280, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_VEH_MOVE_DOWN = 281, -- Index: 281, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_VEH_GUN_LEFT = 282, -- Index: 282, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_GUN_RIGHT = 283, -- Index: 283, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_GUN_UP = 284, -- Index: 284, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_GUN_DOWN = 285, -- Index: 285, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_LOOK_LEFT = 286, -- Index: 286, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_LOOK_RIGHT = 287, -- Index: 287, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_REPLAY_START_STOP_RECORDING = 288, -- Index: 288, Default QWERTY: F1, Xbox Controller: A
    INPUT_REPLAY_START_STOP_RECORDING_SECONDARY = 289, -- Index: 289, Default QWERTY: F2, Xbox Controller: X
    INPUT_SCALED_LOOK_LR = 290, -- Index: 290, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_SCALED_LOOK_UD = 291, -- Index: 291, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_SCALED_LOOK_UP_ONLY = 292, -- Index: 292, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_SCALED_LOOK_DOWN_ONLY = 293, -- Index: 293, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_SCALED_LOOK_LEFT_ONLY = 294, -- Index: 294, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_SCALED_LOOK_RIGHT_ONLY = 295, -- Index: 295, Default QWERTY: (NONE), Xbox Controller: RIGHT STICK
    INPUT_REPLAY_MARKER_DELETE = 296, -- Index: 296, Default QWERTY: DELETE, Xbox Controller: X
    INPUT_REPLAY_CLIP_DELETE = 297, -- Index: 297, Default QWERTY: DELETE, Xbox Controller: Y
    INPUT_REPLAY_PAUSE = 298, -- Index: 298, Default QWERTY: SPACEBAR, Xbox Controller: A
    INPUT_REPLAY_REWIND = 299, -- Index: 299, Default QWERTY: ARROW DOWN, Xbox Controller: LB
    INPUT_REPLAY_FFWD = 300, -- Index: 300, Default QWERTY: ARROW UP, Xbox Controller: RB
    INPUT_REPLAY_NEWMARKER = 301, -- Index: 301, Default QWERTY: M, Xbox Controller: A
    INPUT_REPLAY_RECORD = 302, -- Index: 302, Default QWERTY: S, Xbox Controller: (NONE)
    INPUT_REPLAY_SCREENSHOT = 303, -- Index: 303, Default QWERTY: U, Xbox Controller: DPAD UP
    INPUT_REPLAY_HIDEHUD = 304, -- Index: 304, Default QWERTY: H, Xbox Controller: R3
    INPUT_REPLAY_STARTPOINT = 305, -- Index: 305, Default QWERTY: B, Xbox Controller: (NONE)
    INPUT_REPLAY_ENDPOINT = 306, -- Index: 306, Default QWERTY: N, Xbox Controller: (NONE)
    INPUT_REPLAY_ADVANCE = 307, -- Index: 307, Default QWERTY: ARROW RIGHT, Xbox Controller: DPAD RIGHT
    INPUT_REPLAY_BACK = 308, -- Index: 308, Default QWERTY: ARROW LEFT, Xbox Controller: DPAD LEFT
    INPUT_REPLAY_TOOLS = 309, -- Index: 309, Default QWERTY: T, Xbox Controller: DPAD DOWN
    INPUT_REPLAY_RESTART = 310, -- Index: 310, Default QWERTY: R, Xbox Controller: BACK
    INPUT_REPLAY_SHOWHOTKEY = 311, -- Index: 311, Default QWERTY: K, Xbox Controller: DPAD DOWN
    INPUT_REPLAY_CYCLEMARKERLEFT = 312, -- Index: 312, Default QWERTY: [, Xbox Controller: DPAD LEFT
    INPUT_REPLAY_CYCLEMARKERRIGHT = 313, -- Index: 313, Default QWERTY: ], Xbox Controller: DPAD RIGHT
    INPUT_REPLAY_FOVINCREASE = 314, -- Index: 314, Default QWERTY: NUMPAD +, Xbox Controller: RB
    INPUT_REPLAY_FOVDECREASE = 315, -- Index: 315, Default QWERTY: NUMPAD -, Xbox Controller: LB
    INPUT_REPLAY_CAMERAUP = 316, -- Index: 316, Default QWERTY: PAGE UP, Xbox Controller: (NONE)
    INPUT_REPLAY_CAMERADOWN = 317, -- Index: 317, Default QWERTY: PAGE DOWN, Xbox Controller: (NONE)
    INPUT_REPLAY_SAVE = 318, -- Index: 318, Default QWERTY: F5, Xbox Controller: START
    INPUT_REPLAY_TOGGLETIME = 319, -- Index: 319, Default QWERTY: C, Xbox Controller: (NONE)
    INPUT_REPLAY_TOGGLETIPS = 320, -- Index: 320, Default QWERTY: V, Xbox Controller: (NONE)
    INPUT_REPLAY_PREVIEW = 321, -- Index: 321, Default QWERTY: SPACEBAR, Xbox Controller: (NONE)
    INPUT_REPLAY_TOGGLE_TIMELINE = 322, -- Index: 322, Default QWERTY: ESC, Xbox Controller: (NONE)
    INPUT_REPLAY_TIMELINE_PICKUP_CLIP = 323, -- Index: 323, Default QWERTY: X, Xbox Controller: (NONE)
    INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP = 324, -- Index: 324, Default QWERTY: C, Xbox Controller: (NONE)
    INPUT_REPLAY_TIMELINE_PLACE_CLIP = 325, -- Index: 325, Default QWERTY: V, Xbox Controller: (NONE)
    INPUT_REPLAY_CTRL = 326, -- Index: 326, Default QWERTY: LEFT CTRL, Xbox Controller: (NONE)
    INPUT_REPLAY_TIMELINE_SAVE = 327, -- Index: 327, Default QWERTY: F5, Xbox Controller: (NONE)
    INPUT_REPLAY_PREVIEW_AUDIO = 328, -- Index: 328, Default QWERTY: SPACEBAR, Xbox Controller: RT
    INPUT_VEH_DRIVE_LOOK = 329, -- Index: 329, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_VEH_DRIVE_LOOK2 = 330, -- Index: 330, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_VEH_FLY_ATTACK2 = 331, -- Index: 331, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: (NONE)
    INPUT_RADIO_WHEEL_UD = 332, -- Index: 332, Default QWERTY: MOUSE DOWN, Xbox Controller: RIGHT STICK
    INPUT_RADIO_WHEEL_LR = 333, -- Index: 333, Default QWERTY: MOUSE RIGHT, Xbox Controller: RIGHT STICK
    INPUT_VEH_SLOWMO_UD = 334, -- Index: 334, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: LEFT STICK
    INPUT_VEH_SLOWMO_UP_ONLY = 335, -- Index: 335, Default QWERTY: SCROLLWHEEL UP, Xbox Controller: LEFT STICK
    INPUT_VEH_SLOWMO_DOWN_ONLY = 336, -- Index: 336, Default QWERTY: SCROLLWHEEL DOWN, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE = 337, -- Index: 337, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_HYDRAULICS_CONTROL_LEFT = 338, -- Index: 338, Default QWERTY: A, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_RIGHT = 339, -- Index: 339, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_UP = 340, -- Index: 340, Default QWERTY: LEFT SHIFT, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_DOWN = 341, -- Index: 341, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_UD = 342, -- Index: 342, Default QWERTY: D, Xbox Controller: LEFT STICK
    INPUT_VEH_HYDRAULICS_CONTROL_LR = 343, -- Index: 343, Default QWERTY: LEFT CTRL, Xbox Controller: LEFT STICK
    INPUT_SWITCH_VISOR = 344, -- Index: 344, Default QWERTY: F11, Xbox Controller: DPAD RIGHT
    INPUT_VEH_MELEE_HOLD = 345, -- Index: 345, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_MELEE_LEFT = 346, -- Index: 346, Default QWERTY: LEFT MOUSE BUTTON, Xbox Controller: LB
    INPUT_VEH_MELEE_RIGHT = 347, -- Index: 347, Default QWERTY: RIGHT MOUSE BUTTON, Xbox Controller: RB
    INPUT_MAP_POI = 348, -- Index: 348, Default QWERTY: SCROLLWHEEL BUTTON (PRESS), Xbox Controller: Y
    INPUT_REPLAY_SNAPMATIC_PHOTO = 349, -- Index: 349, Default QWERTY: TAB, Xbox Controller: X
    INPUT_VEH_CAR_JUMP = 350, -- Index: 350, Default QWERTY: E, Xbox Controller: L3
    INPUT_VEH_ROCKET_BOOST = 351, -- Index: 351, Default QWERTY: E, Xbox Controller: L3
    INPUT_VEH_FLY_BOOST = 352, -- Index: 352, Default QWERTY: LEFT SHIFT, Xbox Controller: L3
    INPUT_VEH_PARACHUTE = 353, -- Index: 353, Default QWERTY: SPACEBAR, Xbox Controller: A
    INPUT_VEH_BIKE_WINGS = 354, -- Index: 354, Default QWERTY: X, Xbox Controller: A
    INPUT_VEH_FLY_BOMB_BAY = 355, -- Index: 355, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_VEH_FLY_COUNTER = 356, -- Index: 356, Default QWERTY: E, Xbox Controller: DPAD RIGHT
    INPUT_VEH_TRANSFORM = 357 -- Index: 357, Default QWERTY: X, Xbox Controller: A
}